name: 'build-test'
on:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.2.0
      - run: |
          npm install
      - run: |
          npm run all
      - name: test
        uses: ./
        with:
          command: echo ${PR_NUMBER}
      - name: Semantic-release
        if: github.ref == 'refs/heads/main'
        run: npm run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
